In [3]:
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import ipykernel
import sklearn

print("Numpy Version: ",np.__version__)
print("Pandas Version: ",pd.__version__)
print("Matplotlib Version: ",matplotlib.__version__)
print("Sklearn Version: ",sklearn.__version__)
print("ipykernel Version: ",ipykernel.__version__)

Numpy Version:  2.0.2
Pandas Version:  2.3.3
Matplotlib Version:  3.9.4
Sklearn Version:  1.6.1
ipykernel Version:  6.31.0


# 🔹 What is Machine Learning?

Machine Learning (ML) is a sub-field of Artificial Intelligence (AI) where computers **learn patterns from data** and use those patterns to:

- Make predictions  
- Make decisions  
- Classify items  
- Generate new data  

### 💡 Simple Explanation

Instead of writing rules manually (traditional programming),  
ML automatically **learns the rules from data**.

### 🧠 Traditional Programming vs ML

| Traditional Programming | Machine Learning |
|------------------------|------------------|
| Programmer writes rules manually | Machine learns rules from data |
| Input → Rules → Output | Input → Output → Algorithm learns rules |
| Hard for complex tasks | Excellent for complex patterns |

### ✔ Example  
If you want a computer to recognize a cat:

**Traditional programming:**  
You must write rules like:  
- If ears = pointy  
- If eyes = oval  
- If whiskers = long  
This is impossible to code perfectly.

**Machine Learning:**  
Give the system **100,000 images** of cats 🐱 and not-cats.  
The ML model learns the features automatically.

This is the power of ML.


In [4]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

# Load dataset
iris = load_iris()
X = iris.data
y = iris.target

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Train a simple classifier
model = DecisionTreeClassifier()
model.fit(X_train, y_train)

# Predict
model.predict(X_test[:5])


array([1, 1, 1, 0, 1])

# ✔ Types of Machine Learning

Machine Learning is mainly divided into 3 major types:

1. **Supervised Learning** 🧠  
2. **Unsupervised Learning** 🔍  
3. **Reinforcement Learning** 🎮  

Let's explore each with examples and code.


# 🧠 1. Supervised Learning

Supervised Learning is when the dataset contains:
- **Input features (X)**
- **Output labels (y)**

The model learns the mapping:  
### `X → y`

### ✔ Examples:
- Predicting house price → (X = size, y = price)
- Classifying email as spam or not spam
- Predicting if a customer will buy a product
- Recognizing handwritten digits (0–9)

### 🏆 Supervised learning is used for:
1. **Classification** → Output is a category  
   Example: “Cat or Dog”, “Spam or Not Spam”

2. **Regression** → Output is a number  
   Example: House price prediction


In [5]:
# Example: Classifying iris flowers

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

# Load dataset
iris = load_iris()
X = iris.data
y = iris.target

# Split into train/test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

# Train a KNN model
model = KNeighborsClassifier(n_neighbors=3)
model.fit(X_train, y_train)

# Test accuracy
accuracy = model.score(X_test, y_test)
accuracy


0.9555555555555556

In [6]:
# Example: Linear Regression

from sklearn.linear_model import LinearRegression
import numpy as np

# Fake example data
X = np.array([[1], [2], [3], [4], [5]])  # Study hours
y = np.array([40, 50, 60, 70, 80])       # Exam marks

model = LinearRegression()
model.fit(X, y)

# Predict marks for 6 hours of study
model.predict([[6]])


array([90.])

# 🔍 2. Unsupervised Learning

Unsupervised Learning is when the dataset has:
- **Input features (X)**
- ❌ No labels (no y)**

The model tries to find hidden patterns in data.

### ✔ When is it used?
- Grouping similar items (clustering)
- Reducing high-dimensional data
- Detecting unusual patterns (anomalies)

### 🏆 Examples:
- Grouping customers based on buying behavior
- Clustering news articles by topic
- Segmenting images
- Recommender systems (Netflix, Amazon)

Most common algorithms:
- K-Means Clustering  
- Hierarchical Clustering  
- PCA (Dimensionality Reduction)  


In [7]:
from sklearn.cluster import KMeans
import numpy as np

# Sample 2D data points
X = np.array([
    [1, 2], [1, 3], [2, 2],
    [8, 9], [9, 8], [8, 10]
])

# Create 2 clusters
kmeans = KMeans(n_clusters=2)
kmeans.fit(X)

# Cluster labels
kmeans.labels_


array([1, 1, 1, 0, 0, 0], dtype=int32)

In [8]:
from sklearn.decomposition import PCA
from sklearn.datasets import load_digits

digits = load_digits()
X = digits.data

pca = PCA(n_components=2)
reduced = pca.fit_transform(X)

reduced[:5]  # First 5 transformed samples


array([[ -1.25946645, -21.27488348],
       [  7.9576113 ,  20.76869896],
       [  6.99192297,   9.95598641],
       [-15.90610526,  -3.33246429],
       [ 23.30686741,  -4.26906083]])

# 🎮 3. Reinforcement Learning (RL)

Reinforcement Learning is a type of ML where:

- An **agent** interacts with an **environment**  
- Takes **actions**  
- Receives **rewards or penalties**  
- Learns the best action strategy (policy)

### RL Loop:
State → Action → Reward → Next State → Learn

### ✔ Real-world examples:
- Playing games (Chess, Go, Atari games)  
- Self-driving cars  
- Robotics  
- Stock trading bots  
- Google AlphaGo  

### ✔ Key Concepts:
- **Agent:** Learner  
- **Environment:** World in which agent acts  
- **Action:** Step taken  
- **Reward:** Feedback signal  
- **Policy:** What action to take  
- **Episode:** One full run/game  

In [9]:
import random

rewards = {
    "left": -1,
    "right": +1
}

# Agent chooses action randomly (exploration)
for i in range(5):
    action = random.choice(["left", "right"])
    reward = rewards[action]
    print(f"Action: {action}, Reward: {reward}")


Action: left, Reward: -1
Action: left, Reward: -1
Action: left, Reward: -1
Action: right, Reward: 1
Action: left, Reward: -1


# ✅ Summary

### You learned:

### 🔹 What Machine Learning is  
### 🔹 Supervised Learning  
✔ Classification  
✔ Regression  

### 🔹 Unsupervised Learning  
✔ Clustering  
✔ PCA  

### 🔹 Reinforcement Learning  
✔ Agents  
✔ Actions  
✔ Rewards  

These concepts are the foundation of Machine Learning.  
Next, we will move to **Data Splitting, Overfitting/Underfitting, and Regularization**.
